// module.exports.database = require('./database')
module.exports.gamemodes = require('./gamemodes')
module.exports.matchmaker = require('./matchmaker')
module.exports.objects = require('./objects')
module.exports.socket = require('./socket')
